# Workflow name
name: test4People:
# When it will be triggered
# And in which branch
  pull_request:
  push:
    branches:
      - main
# Where will they run
jobs:
  build:

    runs-on: ubuntu-latest
